#This file stores configuration options for Oculus, such as the currently active shaderpack
#Tue Dec 30 17:09:19 MSK 2025
enableDebugOptions=false
colorSpace=SRGB
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1 + EuphoriaPatches_1.6.5
