#This file stores configuration options for Oculus, such as the currently active shaderpack
#Mon Dec 29 22:24:40 MSK 2025
enableDebugOptions=false
colorSpace=SRGB
disableUpdateMessage=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.5.1 + EuphoriaPatches_1.6.5
